### PR TITLE
Added shape and color settings

### PR DESCRIPTION
**Pull request by matteosist**
Added possibility to change shape type and wave color.

### CODE REVIEW

**Comment by Alok-Sharma** [comment]
I'm not sure when this would get merged, but is there any way I can set the color for now? Sorry for being impatient.

**Comment by SleeplessByte** [comment]
@Alok-Sharma you can checkout @matteosist repo to get their code changes

**Comment by Alok-Sharma** [comment]
@SleeplessByte thanks!

**Comment by gelitenight** [comment]
@matteosist I've merged your code. Thanks!

**Pull request merged**
